const AdjacentNodes = new Map<string, Set<string>>([
    ["Alabama", new Set(["Mississippi", "Tennessee", "Georgia", "Florida"])],
    ["Alaska", new Set(["Washington", "Hawaii"])],
    ["Arizona", new Set(["Utah", "New Mexico"])],
    ["Arkansas", new Set(["Missouri", "Oklahoma", "Texas", "Louisiana"])],
    ["California", new Set(["Hawaii", "Oregon", "Nevada"])],
    ["Colorado", new Set(["Wyoming", "Nebraska", "Kansas", "Oklahoma", "New Mexico", "Utah"])],
    ["Dakotas", new Set(["Montana", "Wyoming", "Nebraska", "Iowa", "Minnesota"])],
    ["Florida", new Set(["Alabama", "Georgia", "Puerto Rico"])],
    ["Georgia", new Set(["Alabama", "Tennessee", "Florida", "South Carolina"])],
    ["Hawaii", new Set(["Alaska", "California"])],
    ["Idaho", new Set(["Washington", "Oregon", "Nevada", "Utah"])],
    ["Illinois", new Set(["Wisconsin", "Iowa", "Indiana"])],
    ["Indiana", new Set(["Michigan", "Illinois", "Ohio"])],
    ["Iowa", new Set(["Minnesota", "Dakotas", "Nebraska", "Missouri", "Illinois"])],
    ["Kansas", new Set(["Nebraska", "Colorado", "Oklahoma", "Missouri"])],
    ["Kentucky", new Set(["Ohio", "West Virginia", "Tennessee"])],
    ["Louisiana", new Set(["Texas", "Arkansas", "Mississippi"])],
    ["Maine", new Set(["Vermont"])],
    ["Maryland", new Set(["Pennsylvania", "New Jersey", "West Virginia", "Virginia"])],
    ["Massachusetts", new Set(["New York", "Vermont"])],
    ["Michigan", new Set(["Wisconsin", "Indiana", "Ohio"])],
    ["Minnesota", new Set(["Dakotas", "Iowa", "Wisconsin"])],
    ["Mississippi", new Set(["Tennessee", "Alabama", "Louisiana"])],
    ["Missouri", new Set(["Iowa", "Nebraska", "Kansas", "Oklahoma", "Arkansas"])],
    ["Montana", new Set(["Wyoming", "Dakotas", "Idaho"])],
    ["Nebraska", new Set(["Dakotas", "Wyoming", "Colorado", "Kansas", "Missouri", "Iowa"])],
    ["Nevada", new Set(["Oregon", "California", "Idaho", "Utah"])],
    ["New Jersey", new Set(["New York", "Pennsylvania", "Maryland"])],
    ["New Mexico", new Set(["Colorado", "Oklahoma", "Texas", "Arizona"])],
    ["New York", new Set(["Pennsylvania", "New Jersey", "Vermont", "Massachusetts"])],
    ["North Carolina", new Set(["South Carolina", "Puerto Rico", "Virginia"])],
    ["Ohio", new Set(["Michigan", "Indiana", "Kentucky", "Pennsylvania"])],
    ["Oklahoma", new Set(["Kansas", "Colorado", "New Mexico", "Texas", "Arkansas", "Missouri"])],
    ["Oregon", new Set(["Washington", "Idaho", "California", "Nevada"])],
    ["Pennsylvania", new Set(["Ohio", "New York", "New Jersey", "Maryland"])],
    ["Puerto Rico", new Set(["Florida", "North Carolina"])],
    ["South Carolina", new Set(["Georgia", "North Carolina"])],
    ["Tennessee", new Set(["Kentucky", "Mississippi", "Alabama", "Georgia"])],
    ["Texas", new Set(["New Mexico", "Oklahoma", "Arkansas", "Louisiana"])],
    ["Utah", new Set(["Idaho", "Nevada", "Arizona", "Colorado"])],
    ["Vermont", new Set(["New York", "Massachusetts", "Maine"])],
    ["Virginia", new Set(["North Carolina", "West Virginia", "Maryland"])],
    ["Washington", new Set(["Alaska", "Oregon", "Idaho"])],
    ["West Virginia", new Set(["Virginia", "Kentucky", "Ohio", "Pennsylvania", "Maryland"])],
    ["Wisconsin", new Set(["Minnesota", "Illinois", "Michigan", "Iowa"])],
    ["Wyoming", new Set(["Montana", "Dakotas", "Nebraska", "Colorado"])]
  ]);

export default AdjacentNodes;